	AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
	Dom.create("nome_dom"=>"Organização")
	Dom.create("nome_dom"=>"Missionário")
	Dom.create("nome_dom"=>"Celibato")
	Dom.create("nome_dom"=>"Discernimento")
	Dom.create("nome_dom"=>"Evangelismo")
	Dom.create("nome_dom"=>"Aconselhamento")
	Dom.create("nome_dom"=>"Fé")
	Dom.create("nome_dom"=>"Generosidade")
	Dom.create("nome_dom"=>"Libertação")
	Dom.create("nome_dom"=>"Cura")
	Dom.create("nome_dom"=>"Ensino")
	Dom.create("nome_dom"=>"Linguas")
	Dom.create("nome_dom"=>"Sabedoria")
	Dom.create("nome_dom"=>"Pobreza Voluntária")
	Dom.create("nome_dom"=>"Habilidade Manual")
	Dom.create("nome_dom"=>"Ajuda")
	Dom.create("nome_dom"=>"Hospitalidade")
	Dom.create("nome_dom"=>"Oração")
	Dom.create("nome_dom"=>"Interpretação")
	Dom.create("nome_dom"=>"Conhecimento")
	Dom.create("nome_dom"=>"Liderança")
	Dom.create("nome_dom"=>"Sofrimento")
	Dom.create("nome_dom"=>"Misericórdia")
	Dom.create("nome_dom"=>"Milagres")
	Dom.create("nome_dom"=>"Apóstolo")
	Dom.create("nome_dom"=>"Pastoral")
	Dom.create("nome_dom"=>"Profecia")
	Dom.create("nome_dom"=>"Serviço")
	Dom.create("nome_dom"=>"Música")
	Dom.create("nome_dom"=>"Criatividade Artística")
	Grupo.create("titulo_grupo"=>"Sinto-me realizado (a) ao")
	Grupo.create("titulo_grupo"=>"Tenho de me envolver, mais do que fiz até agora, em")
	Grupo.create("titulo_grupo"=>"Tive a experiência de")
	Grupo.create("titulo_grupo"=>"As afirmações a seguir correspondem")
	Grupo.create("titulo_grupo"=>"Para mim")
	Grupo.create("titulo_grupo"=>"Eu estaria disposto a")
	Grupo.create("titulo_grupo"=>"Em relação ao aluno posso imaginar")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"desenvolver planos detalhados para alcançar objetivos definidos.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"me adaptar aos estilos de vida e costumes de pessoas e culturas.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"viver sem cônjuge ou parentes. (Se você é casado assinale Nem um pouco)")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"analisar afirmações de outros cristãos para ver se tendem a levar a igreja de Jesus para desvios.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"falar de Jesus e de meu relacionamento com ele para não cristãos")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"encorajar outras pessoas")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"formular objetivos que parecem irreais para outras pessoas, e depois trabalhar de forma decidida para alcançá-los")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"colocar, de forma generosa, o meu dinheiro e as minhas posses à disposição do Reino de Deus.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"ajudar para que as pessoas sejam libertas de opressões demoníacas.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"orar regularmente pela cura de doentes.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"colaborar na elaboração de materiais que tornem simples e interessante o aprendizado das pessoas.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"orar em línguas.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"ajudar pessoas na reflexão sobre a sua situação.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"adaptar-me a um ível de vida bem humilde.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"trabalhar no conserto e manutenção de coisas.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"trabalhar nos bastidores, em surdina, para apoiar as pessoas que estão realizando um ministério público.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"receber visitas mesmo quando chegam de surpresa, preparar comida e oferecer uma boa acolhida para eles.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"orar por uma hora ou mais.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"tentar entender a oração em línguas de uma outra pessoa para perceber o que Deus quer no dizer através dela.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"gastar muito tempo no estudo de livros procurando adquirir novos lançamentos.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"liderar pessoas de tal forma que se engajem em um projeto que conduza a um objetivo comum.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"mostrar uma atitude positiva em meio ao sofrimento.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"preocupar-me com pessoas que estão à margem da sociedade.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"orar por coisas que vão contra as leis da natureza.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"engajar-me de tal forma nos problemas de outras igrejas procurando contribuir para se encontrar soluções.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"preocupar-me com o bem espiritual de outros cristãos e acompanhá-los por um longo tempo.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"servir de canal por meio da qual Deus dá orientações claras em uma determinada situação.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"aceitar serviços pequenos e aparentemente insignificantes na igreja.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"dar tudo de mim para desenvolver as minhas habilidades musicais.")
	Pergunta.create("grupo_id"=>1, "titulo_pergunta"=>"expressar as minhas idéias e concepções por meio da arte (teatro, desenho, pantomina, etc).")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"planejar projetos para a igreja, organizá-los e achar as pessoas para a sua implementação.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"manter contatos com pessoas de outras culturas")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"pensar se é a vontade de Deus que eu permaneça solteiro (a). (Se você é casado (a) assinale a coluna da direita).")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"analisar as palavras de outros cristãos para verificar se estão em concordância com a Bíblia.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"conversar sobre a fé em Jesus Cristo com outras pessoas.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"acompanhar de perto pessoas nas suas necessidades.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"contribuir para que \"pessoas com visão\" deem o tom das coisas da igreja.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"entrar em contato com as pessoas e projetos que dependam da minha ajuda financeira.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"ser usado por Deus na batalha contra poderes demoníacos.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"servir como instrumento por meio do qual Deus dá cura sobrenatural.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"gastar tempo em ensinar conhecimento e aptidões a outras pessoas.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"romper a barreira do racional na comunhão com Deus e adorá-lo por meio de novas línguas.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"ajudar pessoas ou organizações a encontrar formas mais eficientes para alcançar os seus objetivos.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"reduzir consideravelmente o meu padrão de vida.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"fazer algo bem prático para Deus com as minhas mãos.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"apoiar outros cristãos colocando os meus dons a serviço dos seus ministérios.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"oferecer a pessoas estranhas um ambiente agradável na minha casa.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"dedicar muito tempo à oração.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"ser usado para interpretar a oração em línguas de outro cristão para uma língua entendida por todos.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"juntar e avaliar ideia e sugestões que são importantes para o corpo de Cristo.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"ser chamado para tarefas de liderança.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"colocar-me á disposição em situações em que a fé dependa de sacrifícios pessoais.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"ter contato com pessoas que foram negligenciadas ou abandonadas pela sociedade.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"ter a experiência de ser usado por Deus para a realização de milagres e maravilhas.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"trabalhar na fundação de novas igrejas contribuindo para a salvação de pessoas que, de outra forma, não seriam alcançadas.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"acompanhar cristãos para ajudá-los no seu crescimento espiritual.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"esclarecer a outros cristãos qual é a vontade de Deus em uma determinada situação.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"ser chamado (a) quando há necessidade de serem realizadas tarefas bem prtáticas na Igreja.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"servir a Deus com a música.")
	Pergunta.create("grupo_id"=>2, "titulo_pergunta"=>"expressar as minhas ideias de forma criativa e artística (dança, teatro, cerâmica etc.).")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"desenvolver planos que contribuíram para que o trabalho na Igreja fosse feito de uma forma mais eficaz.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"perceber que as pessoas de outas culturas se sentiram atraídas por mim.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"perceber que como solteiro (a) tenho mais energias para trabalhar para Deus. (Se você é casado (a) assinale a coluna da direita).")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"reconhecer falsos motivos por trás de palavras aparentemente muito espirituais de outras pessoas.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"perceber que Deus me usou para levar pessoas a Jesus.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"notar que outras pessoas receberam conforto por meio da minha ajuda.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ver que outros me consideram um \"sonhador\" porque insisto em investir a minha vida em objetivos considerados \"utópicos\".")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ajudar outras pessoas por meio de uma oferta considerável do meu dinheiro.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ver pessoas sendo libertas de opressões demoníacas por meio das minhas orações.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ver como Deus curou por meio das minhas orações pessoas que estavam física ou emocionalmente doentes.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ter a confirmação de outros de que consegui passar-lhes o meu conhecimento de uma forma melhor que a maioria das pessoas.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"orar a Deus em uma língua que me era desconhecida.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"pessoas me pedirem ajuda em um problema complicado e eu ter ajudado para a solução.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ter acesso mais fácil a pessoas pobres porque levo um estilo de vida mais simples.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"poder ajudar pessoas com a habilidade das minhas mãos.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ver pessoas em posição de liderança fazerem melhor o seu trabalho porque realizei trabalhos que eram tarefa delas.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"notar que as pessoa se ncontram com mais frequência na minha casa por se sentirem melhor aqui do que em outros lugares.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"notar a intervenção concreta de Deus quando orei especificamente por algum motivo.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ver que a minha interpretação das linguas foi coerente.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ser o primeiro a dar sugestões que mais tarde foram muito úteis.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"poder incentivar outros cristãos na realização de determinados objetivos.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ver como outras pessoas foram fortalecidas por meio do meu sofrimento.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ajudar pessoas que estavam em necessidade.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ser usado por Deus como instrumento para realizar sinais e milagres.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ver líderes de outras igrejas aceitando e colocando em prática as minhas sugestões.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ajudar cristãos a crescer na fé por meio do meu acompanhamento pessoal e demorado.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"receber a confirmação de cristãos de que a palavra que lhes dei foi uma mensagem de Deus.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"perceber antes de outras pessoas e realizar as tarefas na Igreja.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"ver as pessoas ouvindo atentamente quando usei as minhas habilidades musicais.")
	Pergunta.create("grupo_id"=>3, "titulo_pergunta"=>"usar para a glória de Deus as minhas habilidades criativas (escrever, desenhar, teatro etc.).")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Planejo o meu dia e deixo pouca coisa acontecer por acaso.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Tenho prazer em aprender de outras culturas.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Eu me identifico perfeitamente com as palavras de Paulo, quando ele diz que outros deveriam permanecer solteiros como ele.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Fico profundamente perturbado quando alguém diz algo correto, mas com motivações erradas.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Considero um grande problema o fato de muitos cristãos não falarem da sua fé em Jesus.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Quando pessoa me contam os seus problemas, consigo sentir melhor as suas dificuldades do que outras pessoas.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Para mim não há dúvidas de que Deus cumpre as suas promessas, mesmo quando as evidências dizem o contrário.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"sinto-me tocado quando ouço sobre necessidade financeiras de outras pessoas.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Perturba-me a constatação de que muitas pessoas agem como se não existissem demônios.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Fico mais incomodade que outros cristãos com o fato de que se ora tão pouco pelos doentes em muitas igrejas.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Sofro com o fato de que tão poucos cristãos conseguem passar os seus conhecimentos de forma ilustrativa, interessante e eficiente.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Sinto-me bem em grupos nos quais se ora em línguas.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Tenho prazer em ajudar pessoas a encontrar soluções para os seus problemas.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Fico perturbado pelo padrão de vida tão elevado de muitos cristãos.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Não consigo ver construções, aparelhos, roupa etc., em mau estado de conservação.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Fico satisfeito realizando tarefas que para os outros não são agradáveis.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Tenho alegria em receber visitas inesperadas mesmo quando a minha casa e o meu quarto não estão bem arrumados.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Levo os pedidos de oração de outras pessoas muito a sério e oro por eles regularmente.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Quando alguém fala em línguas, oro para que Deus me dê a interpretação.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Ocupo-me constantemente com verdades bíblicas e com o seu significado para o dia-a-dia.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Em um grupo sem líder eu tomo a iniciativa.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Realatos de mártires cristãos me fascinam.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Quando vejo uma necessidade quero ajudar imediatamente.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Oro para que Deus faça sinais e milagres por meu intermédio como acontecia na época da Igreja Primitiva.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Sinto mais do que outros cristãos a necessidade de promover unidade entre as diferentes igrejas.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Estou perturbado com o fato de que muitos cristãos recebem um acompanhamento tão precário na sua vida pessoal e espiritual.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"oro para que Deus me dê mensagens para outros cristãos com mais regularidade do que aconteceu até agora.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Noto quando outras pessoas estão precisando de ajuda prática e estou disposto a prestá-las.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Entristeço-me quando na igreja se dá pouco valor para a qualidade da música.")
	Pergunta.create("grupo_id"=>4, "titulo_pergunta"=>"Considero importante para os cristãos se engajarem na preservação e no embelezamento do meio-ambiente em que vivem.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"desenvolver, por conta própria, projetos que envolvam negociações e organização.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"fazer contato com pessoas que têm um estilo de vida totalmente diferente do meu.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"abrir mão de construir família. (se você é casado (a) assinale a coluna da direita).")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"discernir se as palavras de uma pessoa são de origem divina, humana ou satânica.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"perceber o momento em que uma pessoa está preparada para aceitar o evangelho.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"aprofundar, em pouco tempo, uma conversa com pessoas que eu não conhecia antes.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"orar e trabalhar por coisas que outros cristãos consideram impossíveis.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"dar regularmente parte do meu dinheiro para o Reino de Deus.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"perceber se há áreas na vida de uma pessoa estão sob domínio demoníaco.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"orar pessoal e concretamente pela cura de doentes.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"transmitir verdades e conceitos de forma lógica, interessante e compreensível para os ouvintes.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"transmitir uma mensagem de Deus (ou uma oração) a outros cristãos em forma de oração em línguas.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"aplicar conhecimento teórico a uma situação concreta.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"viver com um padrão de vida simples.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"resolver problemas práticos que normalmente necessitariam do trabalho de um técnico especializado.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"ajudar outros cristãos na sua tarefa para que possam fazer melhor o seu trabalho.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"transmitir a visitas desconhecidas a sensação de estarem em casa.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"orar semans ou meses seguidos por motivos bem definidos.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"sentir o que Deus quer dizer quando ouço uma mensagem em línguas.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"descobrir, formular e sistematizar fatos que são importantes para a saúde da Igreja.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"delegar tarefas a outras pessoas.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"dispor-me a sofrer por Jesus.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"expressar a pessoas em necessidades o quanto sofro com elas.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"orar por sinais sobrenaturais e milagres.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"aconselhar grupos e igrejas acerca da sua situação espiritual.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"acompanhar pessoalmente um grupo de cristãos e me empenhar pela sua unidade.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"receber orientações de Deus sobre qual é a sua vontade em uma determinada situação.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"aceitar tarefas que não são muito atraentes para outros.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"aprender a tocar um instrumento musical.")
	Pergunta.create("grupo_id"=>5, "titulo_pergunta"=>"colocar em prática formas criativas de comunicação (pintura, teatro, pantomima etc.).")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"participar de treinamento que me ajude a melhorar minhas habilidades de planejamento, organização e delegação de tarefas.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"trabalhar em outro país ou cultura, se tivesse a oportunidade.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"permanecer solteiro para melhor trabalhar para o Reino de Deus. (Se você é casado (a) assinale a coluna da direita).")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"investir muito tempo advertindo pessoas de possíveis perigos.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"participar de um treinamento em que se aprende a levar pessoas a Jesus.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"aprender mais sobre como ajudar pessoas por meio de aconselhamento espiritual.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"aceitar um desafio mesmo que implicasse um alto risco.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"apoiar regularmente com o meu dinheiro cristãos que estão realizando um trabalho digno.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"colocar-me à disposição para a batalha espiritual contra demônios.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"participar de um ministério de oração pelos doentes.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"ler mais sobre comunicação para desenvolver minha capacidade de ensino.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"orar publicamente em línguas se Deus me der esse dom.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"investir muito tempo aconselhando pessoas ou grupos para a tomada de decisões importantes.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"abrir mão de boa comida, casa confortável e roupas caras.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"ajudar no conserto e manutenção de aparelhos ou dependências, se necessário.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"aliviar a carga de irmãos que estão sobrecarregados com muitas atividades, fazendo tarefas que eles deveriam fazer.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"compartilhar mais a minha casa com visitantes do que fiz até agora.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"participar de um grupo que tem o ministério de oração por outras pessoas.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"interpretar publicamente a oração em línguas de outra pessoa se Deus me der a interpretação.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"investir muito tempo no desenvolvimento de novas ideias que contribuam para o progresso da Igreja de Jesus.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"colocar-me à disposição para liderar um grupo grande de cristãos.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"arriscar a aminha vida, se isso for necessário, para o Reino de Deus.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"participar do ministério na Igreja que se dedica especialmente aos abandonados pela sociedade.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"concentrar a minha oração em casos considerados humanamente perdidos.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"intermediar situações de conflito entre igrejas.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"assumir a responsabilidade por um grupo de cristãos.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"transmitir mensagens, mesmo desagradáveis, a irmãos da igreja.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"investir o meu tempo com tarefas na igreja que são as mais urgentes.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"participar de um evento de música na Igreja.")
	Pergunta.create("grupo_id"=>6, "titulo_pergunta"=>"participar de um grupo em que somos ensinados a desenvolver habilidades artísticas.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) tenha prazer em ajudar em uma tarefa relacionada com detalhes de organização.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) teria prazer em viver a maior parte da sua vida em um país ou cultura diferente.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) teria menos dificuldades de permanecer solteiro(a) do que outra pessoa.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) conheça, melhor do que outros, as motivações que estão por trás de um determinado comportamento.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"o chamado específico é falar com não cristãos sobre a fé em Jesus Cristo.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"pessoas o(a) procurem para receber aconselhamento.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) esteja disposto(a) a correr grandes riscos pessoais para alcançar os seus objetivos.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"para ele(a) é mais importante do que para a maioria dos cristãos, apoiar financeiramente projetos cristãos.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) saiba discernir, melhor do que outras pessoas, se algo é de origem humana, satânica ou divina.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"pessoas o(a) procurem mais do que a outras pessoas para que ore por sua cura.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) tenha alegria imensa em ensinar outros cristãos.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) tenha o dom de orar em línguas.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"seja mais fácil para ele(a) resolver problemas complicados de outras pessoas.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) seja mais feliz com poucos bens materiais do que com muitos.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"as suas mãos sejam mais habilidosas do que as da maioria das pessoas.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) tenha prazer em ajudar outras pessoas com tarefas que tomem um tempo considerável.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) seja mais feliz com visitas em casa do que sem.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) sinta mais alegria do que a maioria dos cristãos ao investir muito tempo em oração.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) esteja em condições de interpretar a oração em línguas de outro cristão.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) tenha prazer em investir muito tempo no desenvolvimento de novas idéias.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"o chamado dele(a) seja dar a outros orientações para a sua caminhada.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) tenha mais facilidade de passar por sofrimentos do que outros cristãos.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"seja a sua tarefa específica prestar ajuda prática a pessoas em necessidade.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"Deus o(a) use frequentemente na realização de sinais e milagres.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) seja chamado(a) a dar conselhos na hora de instruir mais pessoas na liderança da igreja.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"que ele(a) tenha muita alegria em acompanhar um grupo de cristãos por um período longo.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"ele(a) seja mais usado(a) por Deus do que outros cristãos para transmitir mensagens à igreja.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"seja mais fácil para ele(a) do que para outros, fazer um trabalho na igreja que é urgente no momento.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"seja o seu chamado específico servir a Deus na área da música.")
	Pergunta.create("grupo_id"=>7, "titulo_pergunta"=>"lhe dê prazer especial engajar-se no campo das artes (pintar, escrever, fazer teatro, etc.).")
	Resposta.create("grupo_id"=>1, "resposta"=>"Nem um pouco", "peso"=>0)
	Resposta.create("grupo_id"=>1, "resposta"=>"Pouco", "peso"=>1)
	Resposta.create("grupo_id"=>1, "resposta"=>"Mais ou menos", "peso"=>2)
	Resposta.create("grupo_id"=>1, "resposta"=>"Muito", "peso"=>3)
	Resposta.create("grupo_id"=>1, "resposta"=>"Muitíssimo", "peso"=>4)
	Resposta.create("grupo_id"=>2, "resposta"=>"Nenhuma vontade", "peso"=>0)
	Resposta.create("grupo_id"=>2, "resposta"=>"Pouca vontade", "peso"=>1)
	Resposta.create("grupo_id"=>2, "resposta"=>"Apenas vontade", "peso"=>2)
	Resposta.create("grupo_id"=>2, "resposta"=>"Grande vontade", "peso"=>3)
	Resposta.create("grupo_id"=>2, "resposta"=>"Enorme vontade", "peso"=>4)
	Resposta.create("grupo_id"=>3, "resposta"=>"Nunca", "peso"=>0)
	Resposta.create("grupo_id"=>3, "resposta"=>"Raramente", "peso"=>1)
	Resposta.create("grupo_id"=>3, "resposta"=>"De vez em quando", "peso"=>2)
	Resposta.create("grupo_id"=>3, "resposta"=>"Frequentemente", "peso"=>3)
	Resposta.create("grupo_id"=>3, "resposta"=>"Muitas vezes", "peso"=>4)
	Resposta.create("grupo_id"=>4, "resposta"=>"Não correspondem", "peso"=>0)
	Resposta.create("grupo_id"=>4, "resposta"=>"Muito pouco", "peso"=>1)
	Resposta.create("grupo_id"=>4, "resposta"=>"Mais ou menos", "peso"=>2)
	Resposta.create("grupo_id"=>4, "resposta"=>"Fortemente", "peso"=>3)
	Resposta.create("grupo_id"=>4, "resposta"=>"Muito fortemente", "peso"=>4)
	Resposta.create("grupo_id"=>5, "resposta"=>"É bem difícil", "peso"=>0)
	Resposta.create("grupo_id"=>5, "resposta"=>"É relativamente difícil", "peso"=>1)
	Resposta.create("grupo_id"=>5, "resposta"=>"Não é nem fácil nem difícil", "peso"=>2)
	Resposta.create("grupo_id"=>5, "resposta"=>"É fácil", "peso"=>3)
	Resposta.create("grupo_id"=>5, "resposta"=>"É muito fácil", "peso"=>4)
	Resposta.create("grupo_id"=>6, "resposta"=>"Nem um pouco", "peso"=>0)
	Resposta.create("grupo_id"=>6, "resposta"=>"Pouco", "peso"=>1)
	Resposta.create("grupo_id"=>6, "resposta"=>"Mais ou menos", "peso"=>2)
	Resposta.create("grupo_id"=>6, "resposta"=>"Muito", "peso"=>3)
	Resposta.create("grupo_id"=>6, "resposta"=>"Muitíssimo", "peso"=>4)
	Resposta.create("grupo_id"=>7, "resposta"=>"que de forma nenhuma", "peso"=>0)
	Resposta.create("grupo_id"=>7, "resposta"=>"que raramente", "peso"=>1)
	Resposta.create("grupo_id"=>7, "resposta"=>"que em algumas situações", "peso"=>2)
	Resposta.create("grupo_id"=>7, "resposta"=>"que", "peso"=>3)
	Resposta.create("grupo_id"=>7, "resposta"=>"muito bem que", "peso"=>4)