Resposta.create([
{ "grupo_id": 1, "resposta": "Nem um pouco", "peso": 0 },
{ "grupo_id": 1, "resposta": "Pouco", "peso": 1 },
{ "grupo_id": 1, "resposta": "Mais ou menos", "peso": 2 },
{ "grupo_id": 1, "resposta": "Muito", "peso": 3 },
{ "grupo_id": 1, "resposta": "Muitíssimo", "peso": 4 },
{ "grupo_id": 2, "resposta": "Nenhuma vontade", "peso": 0 },
{ "grupo_id": 2, "resposta": "Pouca vontade", "peso": 1 },
{ "grupo_id": 2, "resposta": "Apenas vontade", "peso": 2 },
{ "grupo_id": 2, "resposta": "Grande vontade", "peso": 3 },
{ "grupo_id": 2, "resposta": "Enorme vontade", "peso": 4 },
{ "grupo_id": 3, "resposta": "Nunca", "peso": 0 },
{ "grupo_id": 3, "resposta": "Raramente", "peso": 1 },
{ "grupo_id": 3, "resposta": "De vez em quando", "peso": 2 },
{ "grupo_id": 3, "resposta": "Frequentemente", "peso": 3 },
{ "grupo_id": 3, "resposta": "Muitas vezes", "peso": 4 },
{ "grupo_id": 4, "resposta": "Não correspondem", "peso": 0 },
{ "grupo_id": 4, "resposta": "Muito pouco", "peso": 1 },
{ "grupo_id": 4, "resposta": "Mais ou menos", "peso": 2 },
{ "grupo_id": 4, "resposta": "Fortemente", "peso": 3 },
{ "grupo_id": 4, "resposta": "Muito fortemente", "peso": 4 },
{ "grupo_id": 5, "resposta": "É bem difícil", "peso": 0 },
{ "grupo_id": 5, "resposta": "É relativamente difícil", "peso": 1 },
{ "grupo_id": 5, "resposta": "Não é nem fácil nem difícil", "peso": 2 },
{ "grupo_id": 5, "resposta": "É fácil", "peso": 3 },
{ "grupo_id": 5, "resposta": "É muito fácil", "peso": 4 },
{ "grupo_id": 6, "resposta": "Nem um pouco", "peso": 0 },
{ "grupo_id": 6, "resposta": "Pouco", "peso": 1 },
{ "grupo_id": 6, "resposta": "Mais ou menos", "peso": 2 },
{ "grupo_id": 6, "resposta": "Muito", "peso": 3 },
{ "grupo_id": 6, "resposta": "Muitíssimo", "peso": 4 },
{ "grupo_id": 7, "resposta": "que de forma nenhuma", "peso": 0 },
{ "grupo_id": 7, "resposta": "que raramente", "peso": 1 },
{ "grupo_id": 7, "resposta": "que em algumas situações", "peso": 2 },
{ "grupo_id": 7, "resposta": "que", "peso": 3 },
{ "grupo_id": 7, "resposta": "muito bem que", "peso": 4 }
])
